### ISSUE TITLE
Drop Python 3.3 support

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.keyreference#7]

**Comment by hugovk** [comment]
This can be closed, support was dropped in https://github.com/zopefoundation/zope.keyreference/pull/8.

**Comment by jamadden** [comment]
Indeed, #8 has been merged. There hasn't been a PyPI release, though, maybe that's what @icemac meant (I don't have access to do that).

**Comment by mgedmin** [comment]
@jamadden you have PyPI access now ;)

**Comment by jamadden** [comment]
Cool! I'll add some more badges to the readme (so we can easily see what's on PyPI) then I'll do a release.

**Comment by jamadden** [comment]
We don't have any coverage reports enabled. I'll do a PR for that first.

**Comment by jamadden** [comment]
4.2.0 has been [released to PyPI](https://pypi.org/project/zope.keyreference/4.2.0/)
